### PR TITLE
removed failing test and modified/added tests to keep coverage > 90%

### PR DESCRIPTION
**Pull request by HannahKent**

### CODE REVIEW

**Comment by HannahKent** [comment]
@debbieneaeraconsulting @vmayorskiy-ac

**Comment by HannahKent** [comment]
@vmayorskiy-ac @debbieneaeraconsulting solved the test problem :)

**Review by vmayorskiy-al — CHANGES_REQUESTED** [review]
Hi Hannah!

One more bucket change please? (not in your changes - but in original code - sorry!)

Thanks!
-v

**Review by vmayorskiy-al — CHANGES_REQUESTED** [review]
Hi Hannah!

One more bucket name please?

Thanks!
-v

**Comment by HannahKent** [comment]
@vmayorskiy-ac I made the change

**Comment by vmayorskiy-al** [comment]
Hi Hannah! Could you please re-submit with merge to develop branch instead, not master? :)

Thanks!
-v

**Pull request closed without merging**
